Fix a wrong target name in the protobuf/3.0.0/BUILD file.
The "protobuf_python" target references a "protobuf_python_srcs" target in its deps, which does not exist, causing a build error when I tried to run "bazel build //src/main/...":

ERROR: /Users/philwo/src/bazel/third_party/protobuf/3.0.0/BUILD:70:1: in deps attribute of py_library rule //third_party/protobuf/3.0.0:protobuf_python: rule '//third_party/protobuf/3.0.0:protobuf_python_srcs' does not exist. Since this rule was created by the macro 'py_proto_library', the error might have been caused by the macro implementation in /Users/philwo/src/bazel/third_party/protobuf/protobuf.bzl:256:12.

I think the "python_srcs" target should actually be called "protobuf_python_srcs". With that change, the build works.

--
MOS_MIGRATED_REVID=136467485