Rollback of commit 8859adb5fa4b661e91cd17ada4be30e593335585.
*** Reason for rollback ***

Roll-forward with fix.

Tested with `bazel build src:srcs //src/test/...` using a bootstrapped bazel.

Fixes #1923.

RELNOTES[INC]: Non test-only targets can no longer depends on test-only targets.


*** Original change description ***

Automated [] rollback of commit 03fe5805a41035adba8f7ee56192f3b1a34cf99e.

*** Reason for rollback ***

Broke Bazel CI:

ERROR: /home/ci/workspace/Bazel/JAVA_VERSION/1.8/PLATFORM_NAME/linux-x86_64/src/BUILD:284:1: in filegroup rule //src:srcs: non-test target '//src:srcs' depends on testonly target '//src/java_tools/junitrunner/java/com/google/testing/junit/junit4:srcs' and doesn't have testonly attribute set.
ERROR: Analysis of target '//scripts/packages:packages' failed; build aborted.

http://ci.bazel.io/view/Bazel%20b...

***

--
MOS_MIGRATED_REVID=136589937