Automated [] rollback of commit c3d60e8e7a7f6f8cfc6b2ccdf6bb8bb01b7e0041.
*** Reason for rollback ***

Rolling forward after fixing Mac tests, and adding coverage to Kokoro.

*** Original change description ***

Automated [] rollback of commit c9fa1bb50c26490aadece3694659c1754c515a45.

*** Reason for rollback ***

These tests break on Mac: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/561/console
E.g.: 
ERROR: /Users/ci/workspace/bazel-tests/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/src/java_tools/junitrunner/javatests/com/google/testing/junit/runner/BUILD:64:1: Couldn't build file src/java_tools/junitrunner/javatests/com/google/testing/junit/runner/junit4_testbridge_integration_test.runfi...

***

ROLLBACK_OF=147587929

--
PiperOrigin-RevId: 147746587
MOS_MIGRATED_REVID=147746587