Rollback of commit 03fe5805a41035adba8f7ee56192f3b1a34cf99e.
*** Reason for rollback ***

Broke Bazel CI:

ERROR: /home/ci/workspace/Bazel/JAVA_VERSION/1.8/PLATFORM_NAME/linux-x86_64/src/BUILD:284:1: in filegroup rule //src:srcs: non-test target '//src:srcs' depends on testonly target '//src/java_tools/junitrunner/java/com/google/testing/junit/junit4:srcs' and doesn't have testonly attribute set.
ERROR: Analysis of target '//scripts/packages:packages' failed; build aborted.

http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/923/console

*** Original change description ***

Enforce that non test-only targets cannot depends on test-only targets

This behavior was not enforced since we open-sourced Bazel even though this was
documented and the attributed existed.

Also removed the incorrect part from the documentations: we do not enforce
restrictions on javatests package.

Fixes #1923.

RELNOTES[INC]: Non test-only targets can no longer depends on test-only targets.

--
MOS_MIGRATED_REVID=136574806