Rollback of commit 8b4a9e454e72597cd02da74ae63b1095933d901f.
*** Reason for rollback ***

Breaks the Jenkins continuous builds. The error message is a mysterious Skyframe one and it only raised if the Android NDK/SDK is set in the WORKSPACE file:

java.lang.IllegalStateException: ANDROID_NDK_REPOSITORY:@androidndk -> GroupedListHelper{groupedList=[FILE:[/usr/local/google/home/lberki/.cache/bazel/_bazel_lberki/97aa07230f44a76bcaa14338f20a8e2e/external/androidndk/ndk/RELEASE.TXT]/[]], elements=[FILE:...], size=24}, reverseDepsToSignal=ReverseDeps{reverseDeps=REPOSITORY:@androidndk, singleReverseDep=true, dataToConsolidate=null}, lastBuildDirectDeps=null, dirtyDirectDepIterator=null}}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:994)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:496)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



*** Original change description ***

Preserve repositories' rooted paths

This was taking the "right" rooted path, converting it to a path, and then
making the rooted path [/path/to/external/repo/BUILD]/[] (where it should
have been [/path/to/external/repo]/[BUILD]).

--
MOS_MIGRATED_REVID=107768560