Rollback of commit 245a2c29b8a4f3658cf1e2ee57252466b9b9696b.
*** Reason for rollback ***

Makes blaze unable to build //third_party/stl
IllegalArgumentException: complex.h.processed
  at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
  at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
  at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.addObjectFile(CppLinkActionBuilder.java:831)

NOT a clean rollback; conflict in one file (CppCompilationContext.java).
So this also partially rolls back commit 05cb23a1814d82eda07015965bec6dde49bc37f1 (just the change in that file).

*** Original change description ***

Cleanup: store non-code inputs to link actions separately.

--
MOS_MIGRATED_REVID=129798636