Rollback of commit b17a7b869e33966e220da14897b179815e33626a.
*** Reason for rollback ***

Causes NPEs in tests that use AutoValue, on Kokoro and CI.

Bazel uses TestRunner_deploy.jar to run tests. To save time, we use the latest Bazel release to run tests. Therefore, we use a TestRunner_deploy.jar with an AutoValue 1.2 embedded. 
If the test requires AV itself, we use the one from HEAD, which is 1.4-rc1, therefore causing one-definition rule violations.

Once we release a TestRunner without AV (commit a85e35cc12afa142ceb5d4f4e59e2f9aa4065e5d), we can roll forward. 


error: @AutoValue processor threw an exception: java.lang.NullPointerException
  abstract static class AutoValuedClass implements TransitiveInfoProvider {
                  ^
  	at com.google.auto.value.processor.AutoValueProcessor.getFieldOfClasses(AutoValueProcessor.java:566)
  	at com.google.auto.value.processor.AutoValueProcessor.allMethodExcludedAnnotations(AutoValueProcessor.java:818)
  	at com.google.auto.value.processor.AutoValueProcessor.defineVarsForType(AutoValueProcessor.java:763)
  	at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:488)
  	at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:195)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:803)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:715)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2000(JavacProcessingEnvironment.java:93)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1023)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1130)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1141)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:832)
  	at com.sun.tools.javac.main.Main.compile(Main.java:253)
  	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:140)
  	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:132)
  	at com.google.devtools.build.buildjar.AbstractJavaBuilder$1.invokeJavac(AbstractJavaBuilder.java:66)
  	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:81)
  	at com.google.devtools.build.buildjar.AbstractJavaBuilder.compileJavaLibrary(AbstractJavaBuilder.java:69)
  	at com.google.devtools.build.buildjar.AbstractJavaBuilder.run(AbstractJavaBuilder.java:108)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:92)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:70)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:47)

*** Original change description ***

Bazel to use AutoValue 1.4-rc1.
The big improvement is the addition of @AutoValue.CopyAnnotations, which allows AutoValue classes to be exposed to Skylark via @SkylarkModule.

--
MOS_MIGRATED_REVID=139361042