Automated g4 rollback of commit 8f404f6fd3c959bb96e6370f41ac74e37c66387e.
*** Reason for rollback ***

Breaks Java 7 tests:
ERROR: missing input file '@bazel_tools//tools/jdk:JavaBuilder_deploy.jar'

http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=linux-x86_64/670/console

*** Original change description ***

Make Java tool jars available from @bazel_tools.

Now users can point to default Java tool jars in custmized
java_toolchain rule defined in project's BUILD file.

PiperOrigin-RevId: 151699090